name: Validate CFG Files

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.cfg'
  push:
    branches: [ main ]
    paths:
      - '**.cfg'

jobs:
  validate-cfg-files:
    name: Validate CFG Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: GameData
      - name: Validate config files
        uses: KSP-CKAN/KSPMMCfgParser@master
